### ISSUE TITLE
Add an api to check if a type is exactly another type

### ISSUE THREAD

**Issue by jakemac53** [jakemac53/macro_prototype#32]
We have the `isSubtypeOf` api today but there are cases where you want something more like `isExactly`.

The specific use case I ran into is for `autoListenable`. I want to be able to find the widget class for a state class. The way I want to do that is to walk up the super hierarchy until I find the `State` class, and then grab the type argument from that.

```dart
class MyState extends State<MyWidget> {}
```

Today I just ended up doing a String name check.

**Comment by scheglov** [comment]
We [have](https://github.com/dart-lang/sdk/blob/62f73a5bd9d5a03e2e690736b4832230adb60153/pkg/analyzer/lib/dart/element/type.dart#L146) something like this in the analyzer for `InterfaceType`. I believe CFE has something like this as well.

**Comment by jakemac53** [comment]
This is exists now
