### ISSUE TITLE
Some IDEs use `gen` to indicate the output of code generation

### ISSUE THREAD

**Issue by stevemessick** [jakemac53/macro_prototype#42]
IntelliJ, for example, uses `gen` as the default name for the directory that holds code generated by various tools. It might be confusing to use `gen` in the name of input files that are processed by code generators. An alternative might be `src` instead.

**Comment by jakemac53** [comment]
Note that these file names (and entire codegen process) are not indicative of how macros will actually work. It is just how this prototype is implemented. You won't be writing these weird `.gen.dart` file in practice, just the original source file.
