### ISSUE TITLE
Is it already possible to use this package or is it worth waiting a little longer?

### ISSUE THREAD

**Issue by mezoni** [jakemac53/macro_prototype#43]
What is the status of this package?

**Comment by jakemac53** [comment]
See the readme, this is only a prototype of a theoretical macro system. It will never be shipped in this form, and is only meant for people to be able to write some theoretical macros and evaluate the API surface area. Real macros won't require explicit codegen through a separate tool like build_runner.

**Comment by mezoni** [comment]
Thank you.
I asked this question because it is not entirely clear when this will be implemented.
I mean macro programming.
This project is the only reference point, but the development of this project has been suspended.
